version: 2
jobs:
  build:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: my-project-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: my-project-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn test -- --watch=false --no-progress --browsers ChromeHeadless
      - store_test_results:
          path: test-results
    parallelism: 4
workflows:
  version: 2
  workflow:
    jobs:
      - build
